In [1]:
import pandas as pd

In [2]:
URL = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
Table = pd.read_html(URL)

In [3]:
# Scrape the information Table from Wikipedia and read it into a DataFrame
postcode = Table[0]
postcode.head()

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

In [4]:
# Clean up the DataFrame from 'Not Assigned' Boroughs
index = postcode[postcode['Borough']=='Not assigned'].index
postcode.drop(index, inplace=True)
postcode = postcode.reset_index(drop=True)
postcode.head(10)

  Postcode           Borough     Neighbourhood
0      M3A        North York         Parkwoods
1      M4A        North York  Victoria Village
2      M5A  Downtown Toronto      Harbourfront
3      M5A  Downtown Toronto       Regent Park
4      M6A        North York  Lawrence Heights
5      M6A        North York    Lawrence Manor
6      M7A      Queen's Park      Not assigned
7      M9A         Etobicoke  Islington Avenue
8      M1B       Scarborough             Rouge
9      M1B       Scarborough           Malvern

In [11]:
# Group the DataFrame's cells by their Postcode and Borough
postcode.groupby(['Postcode', 'Borough'], sort = False).agg(lambda x: ','.join(x))
postcode.head()

  Postcode           Borough     Neighbourhood
0      M3A        North York         Parkwoods
1      M4A        North York  Victoria Village
2      M5A  Downtown Toronto      Harbourfront
3      M5A  Downtown Toronto       Regent Park
4      M6A        North York  Lawrence Heights